import {initStudy} from './study.js';
import {problemView, casesView, codeBlock} from './problem-view.js';
import {EditorView, basicSetup} from 'codemirror';
import {python} from '@codemirror/lang-python';
import {indentWithTab} from '@codemirror/commands';
import {keymap} from '@codemirror/view';
import {EditorState, Compartment} from '@codemirror/state';
import {HighlightStyle, syntaxHighlighting} from '@codemirror/language';
import {tags} from '@lezer/highlight';

const $=s=>document.querySelector(s);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=$('meta[name="lab-token"]').content;
let state;
try{state=JSON.parse(localStorage.getItem('interview-lab')||'{}')}catch{state={}}
state.drafts??={};state.solved??={};state.history??={};state.times??={};state.debug??={};
let problems=[],current=null,editor,category='全部',difficulty='全部',docTab='statement',consoleTab='result',result=null,jobId=null,paused=false,loadingCode=false,lastTick=Date.now(),openGeneration=0;
const themeSlot=new Compartment();
let study;
const save=()=>{try{localStorage.setItem('interview-lab',JSON.stringify(state));$('#saved').textContent='已保存'}catch{$('#saved').textContent='保存失败';toast('浏览器存储已满，请下载代码备份')}};
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4000)}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':token},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data}
const badge=d=>`<span class="badge ${{'简单':'easy','中等':'medium','困难':'hard'}[d]}">${d}</span>`;
const status=id=>state.solved[id]?'solved':state.drafts[id]?'draft':'new';
const timeString=sec=>`${Math.floor(sec/60).toString().padStart(2,'0')}:${Math.floor(sec%60).toString().padStart(2,'0')}`;
function filters(){const categories=['全部',...new Set(problems.map(p=>p.category))];$('#categories').innerHTML=categories.map(c=>`<button class="filter ${c===category?'active':''}" data-category="${escape(c)}">${escape(c)}<span>${problems.filter(p=>c==='全部'||p.category===c).length}</span></button>`).join('');$('#difficulties').innerHTML=['全部','简单','中等','困难'].map(d=>`<button class="filter ${d===difficulty?'active':''}" data-difficulty="${d}">${d==='全部'?'全部难度':d}<span>${problems.filter(p=>d==='全部'||p.difficulty===d).length}</span></button>`).join('');}
function renderBank(){filters();const term=$('#search').value.toLowerCase().trim(),filter=$('#status-filter').value;const rows=problems.filter(p=>(category==='全部'||p.category===category)&&(difficulty==='全部'||p.difficulty===difficulty)&&(filter==='all'||status(p.id)===filter)&&`${p.title} ${p.id} ${p.category}`.toLowerCase().includes(term));$('#count').textContent=`${rows.length} 道题`;$('#problem-list').innerHTML=rows.map(p=>`<tr data-problem="${p.id}"><td>${String(problems.indexOf(p)+1).padStart(3,'0')}</td><td><button class="problem-link">${escape(p.title)}</button><div class="file">${p.id}.py</div></td><td class="category-cell">${escape(p.category)}</td><td>${badge(p.difficulty)}</td><td><span class="status ${status(p.id)}">${{new:'未开始',draft:'练习中',solved:'✓ 已通过'}[status(p.id)]}</span></td><td class="file">${state.times[p.id]?timeString(state.times[p.id]):'—'}</td></tr>`).join('');$('#empty').hidden=rows.length>0;$('#progress').textContent=`${Object.keys(state.solved).length} / ${problems.length} 已完成`}
function setView(work){$('#library').hidden=true;$('#reference-nav').classList.remove('active');$('#interview-nav').classList.remove('active');$('#bank').hidden=work;$('#workspace').hidden=!work;$('#bank-nav').classList.toggle('active',!work);$('#practice-nav').classList.toggle('active',work);if(!work)renderBank();lastTick=Date.now();editor?.requestMeasure()}
function editorTheme(){const dark=state.theme==='dark';return [EditorView.theme({'&':{color:dark?'#dce5f4':'#253047',backgroundColor:dark?'#142031':'#fff'},'.cm-gutters':{backgroundColor:dark?'#142031':'#fafbfd',color:'#7f8ea3',borderRight:'1px solid '+(dark?'#29394d':'#edf0f5')},'.cm-activeLine':{backgroundColor:dark?'#203044':'#f5f8ff'},'.cm-activeLineGutter':{backgroundColor:dark?'#203044':'#edf3ff'},'.cm-cursor':{borderLeftColor:dark?'#b7d4ff':'#2563eb'},'.cm-selectionBackground':{backgroundColor:dark?'#375679 !important':'#cfe0ff !important'}},{dark}),syntaxHighlighting(HighlightStyle.define([{tag:tags.keyword,color:dark?'#c8a6ff':'#7c3aad'},{tag:tags.string,color:dark?'#9dd5a0':'#247344'},{tag:tags.comment,color:dark?'#90a3bd':'#738297'},{tag:[tags.number,tags.bool],color:dark?'#ffc18c':'#9b4c12'},{tag:tags.definition(tags.variableName),color:dark?'#8fc9ff':'#1f5791'}]))]}
function makeState(code){return EditorState.create({doc:code,extensions:[basicSetup,python(),EditorView.contentAttributes.of({'aria-label':'Python 代码编辑器'}),themeSlot.of(editorTheme()),EditorView.lineWrapping,keymap.of([indentWithTab,{key:'Mod-Enter',run:()=>{run('run');return true}},{key:'Mod-Shift-Enter',run:()=>{run('submit');return true}},{key:'Mod-s',run:()=>{save();toast('代码已保存');return true}}]),EditorView.updateListener.of(update=>{if(update.docChanged&&current&&!loadingCode){state.drafts[current.id]=update.state.doc.toString();save()}})]})}
async function openProblem(id){if(jobId){toast('请先等待当前运行结束或停止运行');return}const generation=++openGeneration;try{const p=await api('/api/problem/'+id);if(generation!==openGeneration)return;current=p;state.last=id;save();result=null;docTab='statement';consoleTab='result';paused=false;$('#pause').textContent='暂停计时';loadingCode=true;if(!editor)editor=new EditorView({state:makeState(state.drafts[id]??p.starter),parent:$('#editor')});else editor.setState(makeState(state.drafts[id]??p.starter));loadingCode=false;$('#filename').textContent=id+'.py';$('#current-title').textContent=p.title;$('#timer').textContent=timeString(state.times[id]||0);$('#run-status').textContent='等待运行';$('#breakpoints').value='';setView(true);renderDoc();renderConsole();location.hash=id;}catch(e){toast(e.message)}}
function renderDoc(){document.querySelectorAll('[data-doc]').forEach(b=>b.classList.toggle('selected',b.dataset.doc===docTab));const p=current;if(!p)return;let html='';if(docTab==='statement'){html=problemView(p,badge);}else if(docTab==='cases'){html=casesView(p);}else{html='<h2>提交记录</h2>'+(state.history[p.id]||[]).map((h,i)=>`<div class="history-row"><span class="${h.passed?'success':'failure'}">${h.passed?'✓ 通过':'× 未通过'}</span> · ${escape(new Date(h.date).toLocaleString())}<div class="muted">${h.count} 个测试 · ${h.elapsed} 秒</div><button data-restore="${i}">恢复这次代码</button></div>`).join('');if(!state.history[p.id]?.length)html+='<p class="muted">还没有提交记录。运行示例不会计为提交。</p>';}$('#document').innerHTML=html}
function defaultDebug(){return 'torch.manual_seed(17)\n'+current.cases[0].setup+'\noutput = solve(*args)\nprint(output)\n'}
function renderConsole(){document.querySelectorAll('[data-console]').forEach(b=>b.classList.toggle('selected',b.dataset.console===consoleTab));let html='';if(consoleTab==='debug'){html=`<textarea class="debug-area" id="debug-code" spellcheck="false" aria-label="自定义 Python 调试代码">${escape(state.debug[current.id]??defaultDebug())}</textarea><div class="debug-bar"><span>可直接调用 solve、print、assert 和 backward()</span><button id="debug-run" ${jobId?'disabled':''}>运行调试</button></div>`;}else if(consoleTab==='stdout'){html=`<pre>${escape(result?[result.stdout,result.error,...(result.cases||[]).filter(c=>!c.passed).map(c=>c.name+'\n'+c.error)].filter(Boolean).join('\n\n')||'没有打印输出或错误。':'运行后显示 print 输出与完整 traceback。')}</pre>`;}else if(consoleTab==='snapshots'){html=result?.snapshots?.length?result.snapshots.map(s=>`<details class="case-row"><summary>第 ${s.line} 行执行前</summary><pre>${escape(Object.entries(s.locals).map(([k,v])=>k+' = '+v).join('\n'))}</pre></details>`).join(''):'<p class="result-empty">在编辑器下方输入行号，例如 6, 9，再运行测试或调试。此处展示到达这些行时的局部变量快照，不暂停程序。</p>';}else if(!result){html=`<div class="result-empty">${jobId?'正在启动 Python 并执行测试…':'写好 solve 后，运行示例检查输出。<br>也可以在「自定义调试」中构造张量，逐步验证。'}</div>`;}else{const cases=result.cases||[];html=`<div class="result-heading ${result.passed?'success':'failure'}">${result.passed?'✓ 测试通过':'× 需要检查'} <span class="small-note">${cases.filter(c=>c.passed).length} / ${cases.length} 通过</span></div>${result.error?'<pre class="failure">'+escape(result.error)+'</pre>':''}`+cases.map(c=>`<details class="case-row" ${c.passed?'':'open'}><summary><span class="${c.passed?'success':'failure'}">${c.passed?'✓':'×'}</span> ${escape(c.name)} <small>${c.seed?'seed '+c.seed+' · ':''}${c.ms??0} ms</small></summary>${c.inputs?'<b>输入</b><pre>'+escape(c.inputs)+'</pre>':''}${c.actual?'<b>实际输出</b><pre>'+escape(c.actual)+'</pre>':''}${c.expected?'<b>期望输出</b><pre>'+escape(c.expected)+'</pre>':''}${c.error?'<pre class="failure">'+escape(c.error)+'</pre>':''}</details>`).join('');}$('#console-content').innerHTML=html}
function busy(value){if(value)jobId='pending';for(const id of ['run','submit','reset','resume'])$('#'+id).disabled=value;$('#stop').hidden=!value;$('#stop').disabled=value;if(value)$('#run-status').textContent='运行中…'}
async function run(mode){if(!current||jobId)return;const problem=current.id,code=editor.state.doc.toString();state.drafts[problem]=code;save();const breakpoints=$('#breakpoints').value.split(',').map(Number).filter(n=>Number.isInteger(n)&&n>0);const custom=$('#debug-code')?.value??state.debug[problem]??defaultDebug();if(mode==='debug'){state.debug[problem]=custom;save()}busy(true);result=null;consoleTab='result';renderConsole();try{const started=await api('/api/run',{problem,code,mode,custom,breakpoints});jobId=started.id;$('#stop').disabled=false;renderConsole();let job;do{await new Promise(resolve=>setTimeout(resolve,350));job=await api('/api/job/'+jobId)}while(job.status!=='done');result=job.result;$('#run-status').textContent=`完成 · ${job.elapsed} 秒`;if(mode==='submit'){state.history[problem]??=[];state.history[problem].unshift({date:new Date().toISOString(),passed:result.passed,count:result.cases?.length||0,elapsed:job.elapsed,code});state.history[problem]=state.history[problem].slice(0,15);if(result.passed)state.solved[problem]=true;save();renderBank();if(docTab==='history')renderDoc()}if(mode==='debug')consoleTab=result.snapshots?.length?'snapshots':'stdout';}catch(e){result={passed:false,error:e.message}}finally{jobId=null;busy(false);renderConsole()}}
$('#search').addEventListener('input',renderBank);$('#status-filter').addEventListener('change',renderBank);
$('#categories').onclick=e=>{const b=e.target.closest('[data-category]');if(b){category=b.dataset.category;renderBank()}};$('#difficulties').onclick=e=>{const b=e.target.closest('[data-difficulty]');if(b){difficulty=b.dataset.difficulty;renderBank()}};
$('#problem-list').onclick=e=>{const row=e.target.closest('[data-problem]');if(row)openProblem(row.dataset.problem)};
$('#bank-nav').onclick=$('#back').onclick=()=>{if(jobId){toast('当前任务继续运行，可在工作台查看结果')}setView(false);location.hash=''};
$('#practice-nav').onclick=$('#resume').onclick=()=>{if(current)setView(true);else openProblem(state.last||'ppo_loss')};
$('#run').onclick=()=>run('run');$('#submit').onclick=()=>run('submit');$('#stop').onclick=async()=>{try{await api('/api/cancel/'+jobId,{});}catch(e){toast(e.message)}};
$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'继续计时':'暂停计时'};
$('#reset').onclick=()=>{if(confirm('重置当前代码为题目模板？已提交的历史记录会保留。'))editor.dispatch({changes:{from:0,to:editor.state.doc.length,insert:current.starter}})};
$('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([editor.state.doc.toString()],{type:'text/x-python'}));const a=document.createElement('a');a.href=url;a.download=current.id+'.py';a.click();URL.revokeObjectURL(url)};
$('#theme').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('dark',state.theme==='dark');editor?.dispatch({effects:themeSlot.reconfigure(editorTheme())});save()};
document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>{docTab=b.dataset.doc;renderDoc()});document.querySelectorAll('[data-console]').forEach(b=>b.onclick=()=>{if($('#debug-code')){state.debug[current.id]=$('#debug-code').value;save()}consoleTab=b.dataset.console;renderConsole()});
$('#document').onclick=async e=>{const anchor=e.target.closest('.doc-outline a');if(anchor){e.preventDefault();$('#document').querySelector(anchor.getAttribute('href')).scrollIntoView({behavior:'smooth',block:'start'});return}if(e.target.hasAttribute('data-open-cases')){docTab='cases';renderDoc();return}if(e.target.id==='show-answer'){try{$('#answer-code').innerHTML=codeBlock((await api('/api/solution/'+current.id)).code);$('#answer-dialog').showModal()}catch(err){toast(err.message)}}if(e.target.dataset.debugCase!==undefined){state.debug[current.id]='torch.manual_seed(17)\n'+current.cases[Number(e.target.dataset.debugCase)].setup+'\nprint(solve(*args))\n';save();consoleTab='debug';renderConsole()}if(e.target.dataset.restore!==undefined){const h=state.history[current.id][Number(e.target.dataset.restore)];editor.dispatch({changes:{from:0,to:editor.state.doc.length,insert:h.code}});toast('已恢复提交代码')}};
$('#console-content').addEventListener('input',e=>{if(e.target.id==='debug-code'){state.debug[current.id]=e.target.value;save()}});$('#console-content').onclick=e=>{if(e.target.id==='debug-run')run('debug')};$('#close-answer').onclick=()=>$('#answer-dialog').close();
$('#divider').onpointerdown=e=>{e.target.setPointerCapture(e.pointerId);const move=e=>{const rect=$('.work-grid').getBoundingClientRect();const width=Math.max(25,Math.min(65,(e.clientX-rect.left)/rect.width*100));$('.work-grid').style.setProperty('--left-width',width+'%');editor.requestMeasure()};e.target.onpointermove=move;e.target.onpointerup=()=>{e.target.onpointermove=null}};
$('#divider').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const grid=$('.work-grid'),old=parseFloat(grid.style.getPropertyValue('--left-width'))||40;grid.style.setProperty('--left-width',Math.max(25,Math.min(65,old+(e.key==='ArrowLeft'?-2:2)))+'%')}};
setInterval(()=>{const now=Date.now();if(current&&!$('#workspace').hidden&&!paused&&!document.hidden){state.times[current.id]=(state.times[current.id]||0)+(now-lastTick)/1000;$('#timer').textContent=timeString(state.times[current.id])}lastTick=now},1000);setInterval(save,10000);window.addEventListener('beforeunload',save);
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(study?.route(id))return;if(!id){setView(false);return}if(current?.id===id){setView(true);return}if(problems.some(p=>p.id===id))openProblem(id)});
document.body.classList.toggle('dark',state.theme==='dark');
try{problems=await api('/api/problems');renderBank();study=initStudy({api,problems,openProblem,showMain:setView,toast});const id=location.hash.slice(1);if(study.route(id)){}else if(problems.some(p=>p.id===id))await openProblem(id)}catch(e){toast('题库加载失败：'+e.message)}
